In [ ]:
#DATA AGGREGATION AND GROUPING
import pandas as pd
#multi-year farm data
data={
    'year':[2020,2020,2020,2021,2021,2021,2022,2022,2022,2023,2023,2023],
    'rainfall':['north','south','east','north','south','east','north','south','east','north','south','east'],
    'crop':['wheat','rice','corn','wheat','rice','corn','wheat','rice','corn','wheat','rice','corn'],
    'yield_tons':[180,228,416,195,245,430,210,250,445,225,260,455],
    'area_ha':[50,45,55,52,46,56,54,48,57,55,49,58],
    'cost_thousand':[85,95,180,90,100,190,95,105,195,100,110,200]
    }
df=pd.DataFrame(data)
print('==agricultural data set==')
print(df)

#group by rainfall
print('\n===analysis by rainfall===')
rainfall_stats=df.groupby('rainfall').agg({
    'yield_tons':'sum',
    'area_ha':'sum',
    'cost_thousand':'sum'
    })
print(rainfall_stats)

#group by crop
print('\n=== analysis by crop===')
crop_stats=df.groupby('crop').agg({
    'yield_tons':['mean','max','min'],
    'cost_thousand':'mean'
    }).round(2)
print(crop_stats)

#multiple grouping rainfall
print('\n===rainfall crop analysis===')
rainfall_crop=df.groupby(['rainfall','crop'])['yield_tons'].mean().round(2)
print(rainfall_crop)

#year over growth
print('\n ===yearly trends===')
yearly=df.groupby('year').agg({
    'yield_tons':'sum',
    'area_ha':'sum'
    })
yearly['yield_per_ha']=(yearly['yield_tons']/yearly['area_ha']).round(2)
print(yearly)

#transform :add group mean to each row
df['rainfall_avg_yield']=df.groupby('rainfall')['yield_tons'].transform('mean').round(2)
df['crop_avg_yield']=df.groupby('crop')['yield_tons'].transform('mean').round(2)
print('\n===transformed data===')
print(df)

print('\n === DATASET WITH GROUP AVERAGES===')
print(df[['year','rainfall','crop','yield_tons','rainfall_avg_yield','crop_avg_yield']].head(6))

#pivot table
print('\n===pivot table:average yield by rainfall and crop===')
pivot=df.pivot_table(values='yield_tons',index='rainfall',columns='crop',aggfunc='mean').round(2)
print(pivot)

#filter groups with high performance
print('\n===high performing rainfalls(avg yield >300)===')
high_rainfalls=df.groupby('rainfall').filter(lambda x:x['yield_tons'].mean()>300)
print(high_rainfalls[['rainfall','crop','yield_tons']].drop_duplicates('rainfall'))

==agricultural data set==
    year region   crop  yield_tons  area_ha  cost_thousand
0   2020  north  wheat         180       50             85
1   2020  south   rice         228       45             95
2   2020   east   corn         416       55            180
3   2021  north  wheat         195       52             90
4   2021  south   rice         245       46            100
5   2021   east   corn         430       56            190
6   2022  north  wheat         210       54             95
7   2022  south   rice         250       48            105
8   2022   east   corn         445       57            195
9   2023  north  wheat         225       55            100
10  2023  south   rice         260       49            110
11  2023   east   corn         455       58            200

===analysis by region===
        yield_tons  area_ha  cost_thousand
region
east          1746      226            765
north          810      211            370
south          983      188            410

=== analysis by crop===
      yield_tons           cost_thousand
            mean  max  min          mean
crop
corn      436.50  455  416        191.25
rice      245.75  260  228        102.50
wheat     202.50  225  180         92.50

===region crop analysis===
region  crop
east    corn     436.50
north   wheat    202.50
south   rice     245.75
Name: yield_tons, dtype: float64

 ===yearly trends===
      yield_tons  area_ha  yield_per_ha
year
2020         824      150          5.49
2021         870      154          5.65
2022         905      159          5.69
2023         940      162          5.80

===transformed data===
    year region   crop  yield_tons  area_ha  cost_thousand  region_avg_yield  \
0   2020  north  wheat         180       50             85            202.50
1   2020  south   rice         228       45             95            245.75
2   2020   east   corn         416       55            180            436.50
3   2021  north  wheat         195       52             90            202.50
4   2021  south   rice         245       46            100            245.75
5   2021   east   corn         430       56            190            436.50
6   2022  north  wheat         210       54             95            202.50
7   2022  south   rice         250       48            105            245.75
8   2022   east   corn         445       57            195            436.50
9   2023  north  wheat         225       55            100            202.50
10  2023  south   rice         260       49            110            245.75
11  2023   east   corn         455       58            200            436.50

    crop_avg_yield
0           202.50
1           245.75
2           436.50
3           202.50
4           245.75
5           436.50
6           202.50
7           245.75
8           436.50
9           202.50
10          245.75
11          436.50

 === DATASET WITH GROUP AVERAGES===
   year region   crop  yield_tons  region_avg_yield  crop_avg_yield
0  2020  north  wheat         180            202.50          202.50
1  2020  south   rice         228            245.75          245.75
2  2020   east   corn         416            436.50          436.50
3  2021  north  wheat         195            202.50          202.50
4  2021  south   rice         245            245.75          245.75
5  2021   east   corn         430            436.50          436.50

===pivot table:average yield by region and crop===
crop     corn    rice  wheat
region
east    436.5     NaN    NaN
north     NaN     NaN  202.5
south     NaN  245.75    NaN

===high performing regions(avg yield >300)===
  region  crop  yield_tons
2   east  corn         416

In [ ]:
import pandas as pd
df=pd.DataFrame({
'department':['HR','sales','IT','sales','IT','HR','sales'],
'employee':['a','b','c','d','e','f','g'],
'salary':[50000,60000,45000,48000,70000,72000,71000],
'experience':[2,4,3,5,6,7,5]
})
#df=pd.DataFrame(data)
print(df)

df1=df.groupby(['department','experience'])
print(df1)

  department employee  salary  experience
0         HR        a   50000           2
1      sales        b   60000           4
2         IT        c   45000           3
3      sales        d   48000           5
4         IT        e   70000           6
5         HR        f   72000           7
6      sales        g   71000           5
<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7cec3ce3e030>

In [ ]:
df1=df.groupby(['department','experience'])
print(df1)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7cec3b2e5c40>

In [50]:
import pandas as pd
data={
'department':['HR','sales','IT','sales','IT','HR','sales'],
'employee':['a','b','c','d','e','f','g'],
'salary':[50000,60000,45000,48000,70000,72000,71000],
'experience':[2,4,3,5,6,7,5]
       }
df=pd.DataFrame(data)
print(df)

# Group by department and experience, then calculate the mean salary
df1_aggregated = df.groupby(['department','experience'])['salary'].mean()
print(df1_aggregated)

  department employee  salary  experience
0         HR        a   50000           2
1      sales        b   60000           4
2         IT        c   45000           3
3      sales        d   48000           5
4         IT        e   70000           6
5         HR        f   72000           7
6      sales        g   71000           5
department  experience
HR          2             50000.0
            7             72000.0
IT          3             45000.0
            6             70000.0
sales       4             60000.0
            5             59500.0
Name: salary, dtype: float64

In [16]:
df.groupby(['department','experience']).sum()

                      employee  salary
department experience
HR         2                 a   50000
           7                 f   72000
IT         3                 c   45000
           6                 e   70000
sales      4                 b   60000
           5                dg  119000

In [17]:
df3=df.groupby('experience').sum()
print(df3)

            department employee  salary
experience
2                   HR        a   50000
3                   IT        c   45000
4                sales        b   60000
5           salessales       dg  119000
6                   IT        e   70000
7                   HR        f   72000

In [18]:
df.groupby('department')['salary'].sum()# aggregation function

department
HR       122000
IT       115000
sales    179000
Name: salary, dtype: int64

In [19]:
df1=df.groupby(['department','experience']).sum()
print(df1)

                      employee  salary
department experience
HR         2                 a   50000
           7                 f   72000
IT         3                 c   45000
           6                 e   70000
sales      4                 b   60000
           5                dg  119000

In [20]:
df2=df.groupby('department').sum()
print(df2)

           employee  salary  experience
department
HR               af  122000           9
IT               ce  115000           9
sales           bdg  179000          14

In [24]:
df3=df.groupby('department')['salary'].mean()
print(df3)

department
HR       61000.000000
IT       57500.000000
sales    59666.666667
Name: salary, dtype: float64

In [25]:
df4=df.groupby('department')['employee'].count()
print(df4)

department
HR       2
IT       2
sales    3
Name: employee, dtype: int64

In [32]:
#multiple aggregation
df5=df.groupby('department')['salary'].agg(['sum','mean','std'])
print(df5)

               sum          mean           std
department
HR          122000  61000.000000  15556.349186
IT          115000  57500.000000  17677.669530
sales       179000  59666.666667  11503.622618

In [29]:
#broadcast group mean to each row
df6=df['dept_avg_salary']=df.groupby('department')['salary'].transform('mean')
print(df6)

0    61000.000000
1    59666.666667
2    57500.000000
3    59666.666667
4    57500.000000
5    61000.000000
6    59666.666667
Name: salary, dtype: float64

In [43]:
#CUSTOM AGGREGATION
df.groupby('department').agg({'salary':'sum','experience':'mean'})

            salary  experience
department
HR          122000    4.500000
IT          115000    4.500000
sales       179000    4.666667

In [51]:
#filtering group
df8=df.groupby('department').filter(lambda x:len(x)>2)
print('===filtering group===')
print(df8)

===filtering group===
  department employee  salary  experience
1      sales        b   60000           4
3      sales        d   48000           5
6      sales        g   71000           5

In [45]:
#pivot tables
df.pivot_table(values='salary',index='department',columns='experience',aggfunc='mean')

experience        2        3        4        5        6        7
department
HR          50000.0      NaN      NaN      NaN      NaN  72000.0
IT              NaN  45000.0      NaN      NaN  70000.0      NaN
sales           NaN      NaN  60000.0  59500.0      NaN      NaN

In [48]:
#DATA AGGREGATION AND GROUPING
import pandas as pd
#multi-year farm data
data={
     'crop':['wheat','rice','corn','wheat','rice','corn','wheat','rice','corn'],
     'rainfall':[50,45,55,52,46,56,54,48,57],
     'yield_tons':[180,228,416,195,245,430,210,250,445],
     'area_ha':[10,25,15,32,16,26,34,18,17],
     }
df=pd.DataFrame(data)
print('==agricultural data set==')
print(df)

#group by rainfall
print('\n===analysis by rainfall===')
gkvk=df.groupby('crop').agg({
    'yield_tons':'sum',
    'area_ha':'sum',
    'rainfall':'sum'
    })
print(gkvk)

#group by crop
print('\n=== analysis by crop===')
crop_stats=df.groupby('crop').agg({
    'yield_tons':['mean','max','min'],
    'rainfall':'mean'
    })
print(crop_stats)

#multiple grouping rainfall
print('\n===rainfall crop analysis===')
mandya=df.groupby(['rainfall','crop'])['yield_tons'].mean()
print(mandya)

#year over growth
print('\n ===yearly trends===')
yearly=df.groupby('crop').agg({
    'yield_tons':'sum',
    'area_ha':'sum'
    })
yearly['yield_per_ha']=(yearly['yield_tons']/yearly['area_ha'])
print(yearly)

#transform :add group mean to each row
df['crop_avg_yield']=df.groupby('crop')['yield_tons'].transform('mean')
print('\n===transformed data===')
print(df)

print('\n === DATASET WITH GROUP AVERAGES===')
print(df[['rainfall','crop','yield_tons','crop_avg_yield']])

#pivot table
print('\n===pivot table:average yield by rainfall and crop===')
pivot=df.pivot_table(values='yield_tons',index='rainfall',columns='crop',aggfunc='mean')
print(pivot)

#filter groups with high performance
print('\n===high performing rainfalls(avg yield >300)===')
high_rainfall=df.groupby('rainfall').filter(lambda x:x['yield_tons'].mean()>300)
print(high_rainfall[['rainfall','crop','yield_tons']].drop_duplicates('rainfall'))

==agricultural data set==
    crop  rainfall  yield_tons  area_ha
0  wheat        50         180       10
1   rice        45         228       25
2   corn        55         416       15
3  wheat        52         195       32
4   rice        46         245       16
5   corn        56         430       26
6  wheat        54         210       34
7   rice        48         250       18
8   corn        57         445       17

===analysis by region===
       yield_tons  area_ha  rainfall
crop
corn         1291       58       168
rice          723       59       139
wheat         585       76       156

=== analysis by crop===
       yield_tons             rainfall
             mean  max  min       mean
crop
corn   430.333333  445  416  56.000000
rice   241.000000  250  228  46.333333
wheat  195.000000  210  180  52.000000

===region crop analysis===
rainfall  crop
45        rice     228.0
46        rice     245.0
48        rice     250.0
50        wheat    180.0
52        wheat    195.0
54        wheat    210.0
55        corn     416.0
56        corn     430.0
57        corn     445.0
Name: yield_tons, dtype: float64

 ===yearly trends===
       yield_tons  area_ha  yield_per_ha
crop
corn         1291       58     22.258621
rice          723       59     12.254237
wheat         585       76      7.697368

===transformed data===
    crop  rainfall  yield_tons  area_ha  crop_avg_yield
0  wheat        50         180       10      195.000000
1   rice        45         228       25      241.000000
2   corn        55         416       15      430.333333
3  wheat        52         195       32      195.000000
4   rice        46         245       16      241.000000
5   corn        56         430       26      430.333333
6  wheat        54         210       34      195.000000
7   rice        48         250       18      241.000000
8   corn        57         445       17      430.333333

 === DATASET WITH GROUP AVERAGES===
   rainfall   crop  yield_tons  crop_avg_yield
0        50  wheat         180      195.000000
1        45   rice         228      241.000000
2        55   corn         416      430.333333
3        52  wheat         195      195.000000
4        46   rice         245      241.000000
5        56   corn         430      430.333333
6        54  wheat         210      195.000000
7        48   rice         250      241.000000
8        57   corn         445      430.333333

===pivot table:average yield by region and crop===
crop       corn   rice  wheat
rainfall
45          NaN  228.0    NaN
46          NaN  245.0    NaN
48          NaN  250.0    NaN
50          NaN    NaN  180.0
52          NaN    NaN  195.0
54          NaN    NaN  210.0
55        416.0    NaN    NaN
56        430.0    NaN    NaN
57        445.0    NaN    NaN

===high performing regions(avg yield >300)===
   rainfall  crop  yield_tons
2        55  corn         416
5        56  corn         430
8        57  corn         445